version: 2.1
workflows:
  version: 2
  test:
    jobs:
      - test
  build:
    jobs:
      - build

executors:
  rust-executor:
    docker:
      - image: cimg/rust:1.54.0

jobs:
  test:
    executor: rust-executor
    steps:
      - checkout
      - run: cargo clippy
      - run: cargo test
  build:
    executor: rust-executor
    steps:
      - checkout
      - run: cargo install cargo-run-script
      - run: cargo run-script optimize